### ISSUE TITLE
Incredible ! MANY VERY THANKS, Magdalena, Edouard! Only a point: Gk alphabetic order

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#141] opened 2016-02-11 12:55 UTC
Does not work at the moment in Greek.
Please, maybe give it, Edouard to Magdalena, in the right order.

Best,
Sophie

**Comment by edouardchiricat** [comment] 2016-02-11 13:27
Dear Sophie, 
Magdalena is currently working on a much detailed sorting function. Each title of the columns will be clickable: by doing this, the entries will be rearranged according to the criterion of thet column: Clicking on Translitteration, you will have the entires organized alphabetically according to the transliteration in Latin alphabet, click on 'Greek' and the entries will be listed in Greek alphabetic order etc. You can have a look at the search results : it will be more or les like that.

**Comment by tuurma** [comment] 2016-02-11 20:49
duplicate of #143

**Closed by tuurma** 2016-02-11 20:49 UTC
