### ISSUE TITLE
Trying to acces Ἀγάνωρ 	Aganōr in order to modify it: "failes to load data"

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#95] opened 2016-02-03 16:29 UTC

**Comment by tuurma** [comment] 2016-02-03 17:23
Looks like it's caused by the fact that Greek form was entered as Latin and vice versa

**Comment by edouardchiricat** [comment] 2016-02-03 17:27
​Probably. And I wanted to open it and correct that....​

Édouard

**Comment by tuurma** [comment] 2016-02-03 18:26
Fixed that one manually, but keep the issue open, need a mechanism to deal with that

**Comment by edouardchiricat** [comment] 2016-02-03 18:29
Maybe a 'Delete' option next to each entry?

Édouard

**Comment by tuurma** [comment] 2016-02-03 18:37
Delete option will be surely necessary anyway from time to time! Good point!

**Comment by tuurma** [comment] 2016-02-23 11:51
Closing now that 'delete' option is in place.

**Closed by tuurma** 2016-02-23 11:51 UTC
