### ISSUE TITLE
Different modalities of access for different types of persons with whom I decide to share

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#155] opened 2016-02-14 20:03 UTC
Dear Magdalena,

It seems important that all people being invited to look at our work do not have, of course, the possibility to edit.
1° Among people, as in Googledocs, we would like to be distinguished:
-simple reading
-commentaries
-editing.

2° And it is important I be the only one to decide who is invited, what type of sharing is authorized and to be able to stop it when the collaborator has finished. Some collaborators, as advanced students writing a PhD, will just work for a month, as it will happen already in the next months. 

3° We will be often 3 to 5 working sometimes simultaneously, never more than 10, I think.

4° Another thing is that we will wait a few months (until May or June) before making the open access/reading online, but if I give access to the jury of my application for fundings, I would like the adress to be given to them being of course for reading only and for a short period (from end of March to June, the end of the process). 

Many thanks for this part of the job, which is not the most urgent, even if I have already a collaborator ready to edit. Can he already work in the same time as Edouard, for example from next Wednesday ?

Best regards,
Sophie

**Comment by tuurma** [comment] 2016-02-23 11:39
duplicate of #169

**Closed by tuurma** 2016-02-23 11:39 UTC
