### ISSUE TITLE
Why no more Semantics in French for the first name Aischidippos ? Many thanks, Magdalena

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#138] opened 2016-02-09 18:00 UTC

**Comment by edouardchiricat** [comment] 2016-02-10 18:30
That's probably because the root has been input for testing purposes, and only the english meanings have been inserted. The problem is now fixed.

**Comment by edouardchiricat** [comment] 2016-02-10 18:31
Unfortunately it is imossible for me  to close the ticket.

**Closed** 2016-02-11 10:17 UTC
