### ISSUE TITLE
Just wanted to thank you so much for the Search window with its wonderfully useful truncation function !!!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#205] opened 2016-03-11 21:11 UTC
Could we have it too in the Advanced Search interface, in the first box, as in the ancient interface?
Actually, as I told Robert Parker and Richard Catling, we need it all of us !

Best,
Sophie

**Comment by tuurma** [comment] 2016-03-29 18:59
Yes, functionality of the old website will be reproduced in this regard.

**Comment by tuurma** [comment] 2016-03-29 19:00
Closing as it's a duplicate of #187 and only indirectly connected with ling. Will put an issue on LGPN tracker.

**Closed by tuurma** 2016-03-29 19:00 UTC
