### ISSUE TITLE
There is still a + after the meaning even if the word has only one root

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#93] opened 2016-02-03 15:01 UTC
When a name has only one root, in the column Semantics there is still a + after the meaning. Eg. magnificent+
That + should be removed.

**Comment by edouardchiricat** [comment] 2016-02-03 15:09
The same happens in the column Structure: adj.+, even if the name has only one root, hence one structural value

**Comment by tuurma** [comment] 2016-02-05 18:19
duplicate of #110

**Closed by tuurma** 2016-02-05 18:19 UTC
