### ISSUE TITLE
LGPN-ling doesn't pick-up gender, att. and chronological information from the prosopographic database for many names

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#166] opened 2016-02-19 18:29 UTC
Eg. Ἁβραγόρα, ῾Αβρέας, Ἁβραγόρας, Ἁβροτέλης, Ἁβρόμαχος, Ἁβροκόμας etc.

**Comment by tuurma** [comment] 2016-04-13 10:52
same as #221, will close this one as a discussion of the issue is already there

**Closed by tuurma** 2016-04-13 10:52 UTC
